/*
 * This Groovy source file was generated by the Gradle 'init' task.
 */
package org.utplsql.gradle.plugin

import spock.lang.Specification
import org.gradle.testkit.runner.GradleRunner

/**
 * A simple functional test for the 'org.utplsql.gradle.plugin.utplsql' plugin.
 */
public class UtPLSQLGradlePluginPluginFunctionalTest extends Specification {
    def "can run task"() {
        given:
        def projectDir = new File("build/functionalTest")
        projectDir.mkdirs()
        new File(projectDir, "settings.gradle") << ""
        new File(projectDir, "build.gradle") << """
plugins {
    id('org.utplsql.gradle.plugin.utplsql')
}
        """

        when:
        def runner = GradleRunner.create()
        runner.forwardOutput()
        runner.withPluginClasspath()
        runner.withArguments("utplsql")
        runner.withProjectDir(projectDir)
        def result = runner.build()

        then:
        result.output.contains("Hello from plugin 'org.utplsql.gradle.plugin.utplsql'")
    }
}
